# Site Settings
title: "Sampson Ikechukwu Ewuzie"
email: "sampson.ewuzie@outlook.com"
description: "Power Systems Engineer | M.Eng Student | Smart Grids & Renewable Integration"
baseurl: ""
url: "https://sampsonewuzie.com"

# Author
author:
  name: "Sampson Ikechukwu Ewuzie"
  email: "sampson.ewuzie@outlook.com"

# Social
social:
  linkedin: "https://www.linkedin.com/in/sampsonewuzie"
  github: "https://github.com/SampsonEwuzzy"

# Build
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Logo
logo: /assets/images/profile.jpg

# Timezone
timezone: Africa/Lagos

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor